//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace issueTrack.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class testdbEntities : DbContext
    {
        public testdbEntities()
            : base("name=testdbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBUser> TBUsers { get; set; }
        public virtual DbSet<TBCreator> TBCreators { get; set; }
        public virtual DbSet<TBRepository> TBRepositories { get; set; }
        public virtual DbSet<TBIssue> TBIssues { get; set; }
        public virtual DbSet<TBReply> TBReplies { get; set; }
    }
}
