//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace issueTrack.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBIssue
    {
        public int FDIssueID { get; set; }
        public string FDCreator { get; set; }
        public int FDRepositoryID { get; set; }
        public string FDIssueTitle { get; set; }
        public string FDIssueContent { get; set; }
        public int FDState { get; set; }
        public System.DateTime FDCreationTimestamp { get; set; }
    
        public virtual TBCreator TBCreator { get; set; }
    }
}
