//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace issueTrack.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBReply
    {
        public int FDReplyID { get; set; }
        public string FDCreator { get; set; }
        public int FDIssueIDOrReplyID { get; set; }
        public int FDReferenceType { get; set; }
        public string FDReplyContent { get; set; }
        public System.DateTime FDCreationTimestamp { get; set; }
    }
}
