//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace issueTrack.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBUser()
        {
            this.TBRepositories = new HashSet<TBRepository>();
        }
    
        public string FDEmailOrPhone { get; set; }
        public string FDNickname { get; set; }
        public byte[] FDPassword { get; set; }
        public System.DateTime FDCreationTimestamp { get; set; }
        public Nullable<System.DateTime> FDUpdateTimestamp { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBRepository> TBRepositories { get; set; }
    }
}
